safe:        false
auto:        false
baseurl:     /

source:      .
destination: ./_site
plugins:     ./_plugins

lsi:         false
pygment: 	 true
permalink:   pretty

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]