safe:        false
auto:        false
baseurl:     /

source:      .
destination: ./_site
plugins_dir:     ./_plugins

lsi:         false
highlighter: rouge
permalink:   pretty

markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]